language: python
python:
  - "3.6"
addons:
  sonarcloud:
    organization: "cdot-cv"
    token: ${SONAR_TOKEN}


script:
  - coverage erase
  - coverage run -m pytest "'translator/source code/translator.py' -i 'translator/sample files/Icone Data/incidents_extended.xml'"
  - coverage xml -i
  - sonar-scanner

