# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- 6666-automatic-gcp-deployment

pool:
  vmImage: ubuntu-latest

variables:
  icone_project_name: 'cdot-oim-wzdx-dev'
  cotrip_project_name: 'cdot-oim-wzdx-prod'
  navjoy_project_name: 'cdot-oim-wzdx-dev'

  icone_function_name: 'auto_icone_translator_ftp'
  cotrip_function_name: 'salesforce-data'
  navjoy_function_name: 'navjoy-568-translator'

steps:

- task: DownloadSecureFile@1
  name: authkey
  displayName: 'Download Service Account Key'
  inputs:
    secureFile: 'GoogleServiceAccountKey.json'
    retryCount: '2'

- script:
    gcloud auth activate-service-account --key-file $(authkey.secureFilePath)
    
    gcloud functions deploy $(icone_function_name) --region=us-central1 --project=$(icone_project_name)
  displayName: 'deploy icone function'

# - script:
#     gcloud auth activate-service-account --key-file $(authkey.secureFilePath)
#     gcloud functions deploy $(cotrip_function_name) --region=us-central1 --project=$(cotrip_project_name)
#   displayName: 'deploy cotrip function'

- script:
    gcloud auth activate-service-account --key-file $(authkey.secureFilePath)
    
    gcloud functions deploy $(navjoy_function_name) --region=us-central1 --project=$(navjoy_project_name)
  displayName: 'deploy navjoy function'
