steps:
  - name: 'python:3.12'
    args:
      - '-c'
      - |
        python -m pip install wheel==0.43.0 setuptools==70.1.1
    entrypoint: sh
  - name: 'python:3.12'
    args:
      - '-c'
      - |
        python -m pip install -r requirements.txt
    entrypoint: sh
  - name: 'python:3.12'
    args:
      - '-c'
      - |
        python setup.py sdist bdist_wheel
    entrypoint: sh
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
    args:
      - '-c'
      - >
        pip install twine

        pip install keyrings.google-artifactregistry-auth

        twine upload --repository-url https://us-central1-python.pkg.dev/cdot-shared-services/cdot-shared-cv-python-public-arpo/ dist/*
    entrypoint: sh
timeout: 1200s
options:
  logging: CLOUD_LOGGING_ONLY
